name: Unified React App Deployment

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Step 1: Determine environment name dynamically
    outputs:
      environment_name: ${{ steps.detect.outputs.environment_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect Deployment Environment
        id: detect
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "environment_name=dev" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "environment_name=qa" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "release" ] && [ "${{ github.event.action }}" == "published" ]; then
            echo "environment_name=production" >> $GITHUB_OUTPUT
          else
            echo "Unknown event, skipping."
            exit 1
          fi

      - name: Set environment
        run: echo "Deploying to environment:${{ steps.detect.outputs.environment_name }}"

      - name: display 
        run: "echo ${{vars.Test}}"
