name: Manual Deployment

on:
  pull_request:
   branches: 
    - main/**
   types: [opened, synchronize]
  push:
   branches:
    - main/**

  release:
   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    #environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  
      - name: Display content environment wise
        run: |
         echo "${{ vars.Test }}"
