name: Deploy SQL Scripts

on:
  workflow_dispatch:  

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      - name: Install SQLCMD
        run: |
          sudo apt-get update
      
          # Install prerequisites
          sudo apt-get install -y curl apt-transport-https debconf-utils gnupg
      
          # Add Microsoft GPG key
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
      
          # Add Microsoft package repository for Ubuntu
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
      
          # Update again
          sudo apt-get update
      
          # Install ODBC 18 + SQLCMD
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18
      
          # Add sqlcmd to PATH
          echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
          echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.profile
              
