name: Reusable Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create env file
        run: |
          echo "TEST=${{ vars.TEST }}" >> test.txt

      - name: Deploy
        run: |
          echo "Deploying to ${{ inputs.environment }} environment..."
          echo "${{ vars.Test }}"
